### PR TITLE
Fix google fonts problem

### PR DESCRIPTION
**Pull request by mbbernstein**
This PR fixes the problem with #40 #39 and #37.

### CODE REVIEW

**Comment by rylanb** [comment]
Any plans to release this fix officially?

**Comment by amanmibra** [comment]
This issue still exists, is it not pushed?

**Comment by AnthonyMichaelc** [comment]
yeah I have a fresh project running and the moment I add `@import "active_skin";` to the active_admin.scss file the admin section is rendered useless/give the malformed url error. Curious if there is a work around while waiting for the fix to get pushed?

**Comment by amanmibra** [comment]
@AnthonyMichaelc it seems like the best we can do is pull directly from the repo like this in your `Gemfile`

```
gem 'active_skin', github: 'SoftwareBrothers/active_skin'
```

**Comment by rjherrera** [comment]
@AnthonyMichaelc as the fix is in master and has not been released, what I did was to replace
```ruby
gem 'active_skin'
```

with 

```ruby
gem 'active_skin', github: 'SoftwareBrothers/active_skin'
```

**Comment by AnthonyMichaelc** [comment]
@rjherrera thanks times a million lol. I had gone away from rails for sometime and knew this had worked before but when I hit this error and searched with no answer was scratching my head. Worked like a charm.

**Pull request merged**
